/**x
 * Custom javascript calls for TBN
 * -------------------------------
 */

jQuery(document).ready(function($) {
	
	// jQuery - adding classes for bootstrap styling. In the most cases the elements
	// where the classes are added are autogenerated from wordpress.
	// -----------------------------------------------------------------------------
	$('.widget_calendar table').addClass('table');
	$('.page-pagination a, .page-pagination span').addClass('btn');


	// js Add the sticky menu
	// -----------------------------------------------------------------------------
	// var $header = $("nav#page-navigation"),
	// $clone = $header.before($header.clone().addClass("clone"));

	// $(window).on("scroll", function() {
	// 	var fromTop = $(window).scrollTop();
	// 	console.log(fromTop);
	// 	$("body").toggleClass("down", (fromTop > 200));
	// });

});